baseURL = "https://templ.limelemon.dev/"
languageCode = "ja"
hasCJKLanguage = true
pygmentsCodeFences = true
rssLimit = 16
summaryLength = 64
enableRobotsTXT = true
title = "Templ"
theme = "mainroad"
pagination.pageSize = 10

disqusShortname = "" # Enable Disqus comments by entering your Disqus shortname
#googleAnalytics = "G-TD6LMVD82W" # Enable Google Analytics by entering your tracking ID 

[Author]
    name = "taqu"
    bio = ""
    avatar = "images/neko.jpg"

[Params]
    description = ""
    opengraph = true
    twitter_cards = false
    readmore = false
    authorbox = false
    toc = false
    pager = true
    post_meta = ["date", "categories"]
    mainSections = ["blog", "article"]
    dateformat = "2006-01-02"
    mathjax = false
    mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
    mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config

[Params.logo]
    subtitle = ""

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["recent", "categories", "taglist", "social", "archive"]

[taxonomies]
    tag = "tags"
    category = "categories"
    archive = "archives"

[Params.widgets]
    recent_num = 5
    tags_counter = true

[Params.widgets.social]
    github = "taqu"
    email = "taqu2920.dev@gmail"

[[Menus.main]]
Name = "Top"
URL = "/"
weight = 1

[[Menus.main]]
Name = "Blog"
URL = "/blog/"
weight = 2

[[Menus.main]]
Name = "Articles"
URL = "/article/"
weight = 3

[markup.goldmark.renderer]
unsafe = true

